### ISSUE TITLE
Como gerar o TOKEN e o SECRETS

### ISSUE THREAD

**Issue by jean-felipe** [moip/moip-sdk-ruby#33]
Olá, não ficou claro para mim como gerar o TOKEN e o SECRETS para fazer a autenticação.

Sei que na conta da para gerar uma chave de acesso isso seria o Token para autenticação?
Mas e o secrets do que se trata?

**Comment by joaolucasl** [comment]
Oi @jean-felipe! 

O TOKEN é o mesmo que tem na sua conta (`Configurações > Integração > Chaves de acesso`), e o SECRET é a Chave, logo abaixo:

<img width="539" alt="screen shot 2017-08-07 at 9 30 03 am" src="https://user-images.githubusercontent.com/11381624/29026671-6267d5c6-7b53-11e7-9f84-58ef5d0b4aee.png">

Abraço!
