### ISSUE TITLE
Essa gem Contempla Assinaturas?

### ISSUE THREAD

**Issue by jean-felipe** [moip/moip-sdk-ruby#34]
Boa noite,
Essa gem contempla assinaturas e criação de planos?
Li em alguns lugares que não e em outros que sim, fiquei confuso e não encontrei nenhuma explicação de como fazer aqui também.

**Comment by joaolucasl** [comment]
Olá @jean-felipe! Atualmente, a gem não tem suporte pra assinaturas. Estamos adicionando funcionalidades a essa gem e nossas outras SDKs, então logo, logo essa funcionalidade estará implementada.

Abs!

**Comment by eliasousa** [comment]
Alguma novidade sobre suporte a assinaturas?
