### ISSUE TITLE
Capturar Pagamento Pré-autorizado

### ISSUE THREAD

**Issue by gabrielmm1234** [moip/moip-sdk-ruby#35]
Gostaria de saber se a parte de captura de pagamento pré autorizado está presenta nesta gema.

Não encontrei na documentação, e estou com problemas em mandar uma requisição post utilizando httparty por exemplo.

**Comment by joaolucasl** [comment]
Olá @gabrielmm1234! 
A captura de pagamento pré-autorizado ainda não esta disponível, mas deve entrar no proximo release já que está entre as próximas funcionalidade a serem implementadas. 
O release deve sair entre essa semana e a próxima. Abraço!
