### ISSUE TITLE
[BANKING] Add Bank Accounts

### ISSUE THREAD

**Issue by joaolucasl** [moip/moip-sdk-ruby#57]
The following features should be added to support Bank Accounts:
 - [ ] Create a specific Bank Account
 - [ ] Update a specific Bank Account
 - [ ] Delete a specific Bank Account
 - [ ] Show a specific Bank Account
 - [ ] List All Bank Accounts

You can find the official documentation [here](https://documentao-moip.readme.io/v2.0/reference#contas-bancárias)!

<hr/>

### Implementation Tips:
You can draw inspiration from [this PR](https://github.com/moip/moip-sdk-ruby/pull/50/files). Don't forget to write good tests, and to document it on our `README`

**Comment by ankitbhardwaj78** [comment]
can i work on it @joaolucasl

**Comment by joaolucasl** [comment]
Sure! Go ahead @ankitbhardwaj78! Just bear in mind the REST API docs I linked to are in Portuguese, if that's not a problem for you :)
